// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlPa6GDQYSf_qZ7s3vzhk_2SVfJgHYc3Y',
    appId: '1:1085295322700:web:1edc278a6ccb153085b6e9',
    messagingSenderId: '1085295322700',
    projectId: 'chat-app-8686d',
    authDomain: 'chat-app-8686d.firebaseapp.com',
    storageBucket: 'chat-app-8686d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlPa6GDQYSf_qZ7s3vzhk_2SVfJgHYc3Y', // ✅ UPDATED
    appId: '1:1085295322700:web:1edc278a6ccb153085b6e9',
    messagingSenderId: '1085295322700',
    projectId: 'chat-app-8686d',
    storageBucket: 'chat-app-8686d.appspot.com',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpOUnmPNIUzGcBBwpXdS9DX_2o5qwWSzY',
    appId: '1:1085295322700:ios:b5a21b4c9035f60985b6e9',
    messagingSenderId: '1085295322700',
    projectId: 'chat-app-8686d',
    storageBucket: 'chat-app-8686d.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpOUnmPNIUzGcBBwpXdS9DX_2o5qwWSzY',
    appId: '1:1085295322700:ios:b5a21b4c9035f60985b6e9',
    messagingSenderId: '1085295322700',
    projectId: 'chat-app-8686d',
    storageBucket: 'chat-app-8686d.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlPa6GDQYSf_qZ7s3vzhk_2SVfJgHYc3Y',
    appId: '1:1085295322700:web:8ee65806c7af400f85b6e9',
    messagingSenderId: '1085295322700',
    projectId: 'chat-app-8686d',
    authDomain: 'chat-app-8686d.firebaseapp.com',
    storageBucket: 'chat-app-8686d.firebasestorage.app',
  );

}